FROM ubuntu:20.04 AS base

ENV NODE_ENV testing
ENV PNPM_HOME /root/pnpm

# Install dependencies
RUN apt-get update && \
  apt-get install -y curl gnupg && \
  curl -fsSL https://deb.nodesource.com/setup_20.x | bash - && \
  apt-get install -y nodejs && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/*

RUN npm i -g pnpm

RUN mkdir -p /app
WORKDIR /app

FROM base AS tester

COPY ./tsconfig*.json ./
COPY ./nest-cli.json ./

COPY ./pnpm-lock.yaml ./
COPY ./package.json ./
RUN pnpm install

COPY ./src src

CMD ["pnpm", "run", "test"]